apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: trow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - registry.tomgoring.co.uk
      secretName: quickstart-example-tls
  rules:
    - host: registry.tomgoring.co.uk
      http:
        paths:
          - backend:
              serviceName: trow-svc
              servicePort: 8000
