apiVersion: v1
kind: Service
metadata:
  name: tgcu
spec:
  selector:
    app: tgcu
  ports:
    - name: web-client
      port: 80
      targetPort: 80
    - name: web-api
      port: 3000
      targetPort: 3000
